name: test-go

on:
  workflow_call:
    inputs:
      go-version:
        type: string
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ inputs.go-version }}
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          args: --timeout=10m
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: ${{ inputs.go-version }}
      - name: Run Go tests
        run: |
          go test ./... -cover -json > ./go-test.out
      - name: Format test result
        if: always()
        run: |
          go tool tparse -all -file ./go-test.out
          go tool tparse -all -file ./go-test.out -format markdown >> "$GITHUB_STEP_SUMMARY"
          go clean -testcache
